import base64
import json
import os

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from datetime import datetime, timedelta

SCOPES = [
    "https://www.googleapis.com/auth/calendar"
]

# Next to this file, so it works no matter which folder the server starts in.
SERVICE_ACCOUNT_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "credentials.json"
)

CALENDAR_ID = os.getenv(
    "GOOGLE_CALENDAR_ID",
    "5b958f681e0f3a7ab9316d1955367098481d33c5682578df1fca743a260d0490@group.calendar.google.com"
)


def describe_target():
    """Which calendar this server writes to, without exposing the full id:
    {"calendar": "...d0490@group.calendar.google.com", "source": "env" | "default"}.
    "default" means GOOGLE_CALENDAR_ID is NOT set and the constant above is used,
    the usual reason for two environments (local / Render) writing to different
    calendars."""
    local, _, domain = CALENDAR_ID.partition("@")
    masked = f"…{local[-6:]}@{domain}" if domain else f"…{CALENDAR_ID[-8:]}"
    return {"calendar": masked, "source": "env" if os.getenv("GOOGLE_CALENDAR_ID", "").strip() else "default"}


def http_status(error):
    """HTTP status of a Google API error (None for anything else)."""
    return getattr(getattr(error, "resp", None), "status", None)


def describe_error(error):
    """Short, safe text for a failure (never a token or a message body)."""
    status = http_status(error)
    if status:
        return f"Google Calendar HTTP {status}"
    return f"{type(error).__name__}"


def _read_env(name):
    """Value of an environment variable, tolerating stray spaces or a
    different capitalisation in the NAME (easy to get wrong in a dashboard)."""

    for key, value in os.environ.items():
        if key.strip().upper() == name:
            return value

    return ""


def load_credentials():
    """Service-account credentials for the calendar.

    On a server (Render) the key is NOT stored as a file in the code: put the
    full JSON in the GOOGLE_CREDENTIALS_JSON environment variable (plain JSON,
    or the same JSON encoded as base64). Locally, credentials.json is used.
    """

    raw = _read_env("GOOGLE_CREDENTIALS_JSON").strip().strip('"').strip("'").strip()

    if raw:
        if not raw.startswith("{"):
            raw = base64.b64decode(raw).decode("utf-8")

        # strict=False tolerates real line breaks inside the private key.
        return service_account.Credentials.from_service_account_info(
            json.loads(raw, strict=False),
            scopes=SCOPES
        )

    if not os.path.exists(SERVICE_ACCOUNT_FILE):
        # Names only, never values: helps spot a mistyped variable name.
        similar = sorted(
            key for key in os.environ
            if "GOOGLE" in key.upper() or "CRED" in key.upper()
        )
        raise RuntimeError(
            "Google Calendar is not configured on this server: the "
            "GOOGLE_CREDENTIALS_JSON environment variable is empty or missing "
            f"(similar variable names seen: {similar or 'none'}). Set it to the "
            "full contents of credentials.json and redeploy."
        )

    return service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        scopes=SCOPES
    )


def get_calendar_service():

    credentials = load_credentials()

    return build(
        "calendar",
        "v3",
        credentials=credentials
    )


def create_calendar_event(
    trainer_name,
    client_name,
    client_email,
    session_date,
    session_time,
    session_number=None,
    event_id=None,
    session_id=None
):
    """Creates the event of a client session.

    event_id (base32hex, derived from the session id) makes the call idempotent:
    a second call for the same session finds the event already there (HTTP 409)
    and returns the same id instead of creating a duplicate. session_id is also
    stored in the event's private extended properties."""

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    TRAINER_COLORS = {

        "Carles": "1",
        "David": "2",
        "Guille": "3",
        "Matilda": "4"

    }

    title = f"🏋️ ThundBalance • {client_name}"

    if session_number:

        title += f" ({session_number})"

    event = {

        "summary": title,

        "location": "ThundBalance Personal Training Studio",

        "description": f"""
🏋️ THUNDBALANCE

Client
{client_name}

Trainer
{trainer_name}

Session
{session_number if session_number else "-"}

Email
{client_email}

Duration
60 minutes

Automatically generated by ThundBalance.
""",

        "colorId": TRAINER_COLORS.get(
            trainer_name,
            "1"
        ),

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },
        # "attendees": [
        #
        #     {
        #         "email": client_email
        #     }
        #
        # ],

    }

    if event_id:
        event["id"] = event_id
    if session_id is not None:
        event["extendedProperties"] = {"private": {"thundbalance_session_id": str(session_id)}}

    try:
        created_event = service.events().insert(
            calendarId=CALENDAR_ID,
            body=event
        ).execute()
    except HttpError as error:
        if http_status(error) == 409 and event_id:
            # Already there (this very session was created before). If somebody
            # deleted it in Google, its id is still reserved: bring it back.
            existing = service.events().get(calendarId=CALENDAR_ID, eventId=event_id).execute()
            if existing.get("status") == "cancelled":
                service.events().update(
                    calendarId=CALENDAR_ID, eventId=event_id, body={**event, "status": "confirmed"}
                ).execute()
            print("EVENT ALREADY EXISTED:", event_id)
            return event_id
        raise

    print("EVENT CREATED:", created_event["id"])

    return created_event["id"]

def delete_calendar_event(
    event_id
):

    service = get_calendar_service()

    service.events().delete(
        calendarId=CALENDAR_ID,
        eventId=event_id
    ).execute()

    print("EVENT DELETED:", event_id)


def update_calendar_event(
    event_id,
    session_date,
    session_time
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    print("EVENT ID:", event_id)

    updated_event = {

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        }

    }

    print("UPDATING EVENT...")

    service.events().patch(
        calendarId=CALENDAR_ID,
        eventId=event_id,
        body=updated_event
    ).execute()

    print("EVENT UPDATED:", event_id)



def _trial_event_fields(full_name, email, phone, goal, experience, trainer_name, provisional):
    """Title, description and colour of a trial-session event.

    Provisional (approved, waiting for the client): "[Pendiente] Trial Session · Ana".
    Confirmed by the client: "Trial Session · Ana"."""
    first_name = (str(full_name or "").split() or [""])[0]
    title = f"[Pendiente] Trial Session · {first_name}" if provisional else f"Trial Session · {first_name}"
    state = "Pendiente de confirmación del cliente" if provisional else "Confirmada por el cliente"
    lines = [
        f"Estado: {state}",
        f"Cliente: {full_name}",
        f"Email: {email}",
        f"Teléfono: {phone}",
    ]
    if goal:
        lines.append(f"Objetivos: {goal}")
    if experience:
        lines.append(f"Experiencia: {experience}")
    if trainer_name:
        lines.append(f"Entrenador: {trainer_name}")
    # 5 = yellow while pending, 10 = green once confirmed
    return title, chr(10).join(lines), ("5" if provisional else "10")


def create_trial_session_event(
    full_name,
    email,
    phone,
    goal,
    experience,
    session_date,
    session_time,
    trainer_name=None,
    provisional=False
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    title, description, color = _trial_event_fields(
        full_name, email, phone, goal, experience, trainer_name, provisional
    )

    event = {

        "summary": title,

        "description": description,

        "colorId": color,

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        }

    }

    created_event = service.events().insert(
        calendarId=CALENDAR_ID,
        body=event
    ).execute()

    print("TRIAL EVENT CREATED:", created_event["id"])

    return created_event["id"]


def update_trial_session_event(
    event_id,
    full_name,
    email,
    phone,
    goal,
    experience,
    trainer_name=None,
    provisional=False
):
    """Changes title, description and colour of an existing trial event (the
    same event: confirming never creates a second one). Raises if the event
    does not exist any more; the caller decides what to do then."""

    service = get_calendar_service()

    title, description, color = _trial_event_fields(
        full_name, email, phone, goal, experience, trainer_name, provisional
    )

    service.events().patch(
        calendarId=CALENDAR_ID,
        eventId=event_id,
        body={"summary": title, "description": description, "colorId": color}
    ).execute()

    print("TRIAL EVENT UPDATED:", event_id)


def clear_calendar():

    service = get_calendar_service()

    events = service.events().list(
        calendarId=CALENDAR_ID
    ).execute()

    items = events.get("items", [])

    for event in items:

        try:

            service.events().delete(
                calendarId=CALENDAR_ID,
                eventId=event["id"]
            ).execute()

            print("Deleted:", event["id"])

        except Exception:

            pass

    print("GOOGLE CALENDAR CLEARED")


def list_calendar_events(time_min, time_max):
    """Events between two RFC3339 instants, in Europe/Madrid time.

    Recurring events are expanded and results are paginated until Google has
    no more pages, so a busy month is returned completely.
    """

    service = get_calendar_service()
    events = []
    page_token = None

    while True:
        response = service.events().list(
            calendarId=CALENDAR_ID,
            timeMin=time_min,
            timeMax=time_max,
            singleEvents=True,
            orderBy="startTime",
            timeZone="Europe/Madrid",
            maxResults=250,
            pageToken=page_token
        ).execute()

        events.extend(response.get("items", []))
        page_token = response.get("nextPageToken")

        if not page_token:
            return events
