import base64
import json
import os

from google.oauth2 import service_account
from googleapiclient.discovery import build
from datetime import datetime, timedelta

SCOPES = [
    "https://www.googleapis.com/auth/calendar"
]

# Next to this file, so it works no matter which folder the server starts in.
SERVICE_ACCOUNT_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "credentials.json"
)

CALENDAR_ID = os.getenv(
    "GOOGLE_CALENDAR_ID",
    "5b958f681e0f3a7ab9316d1955367098481d33c5682578df1fca743a260d0490@group.calendar.google.com"
)


def _read_env(name):
    """Value of an environment variable, tolerating stray spaces or a
    different capitalisation in the NAME (easy to get wrong in a dashboard)."""

    for key, value in os.environ.items():
        if key.strip().upper() == name:
            return value

    return ""


def load_credentials():
    """Service-account credentials for the calendar.

    On a server (Render) the key is NOT stored as a file in the code: put the
    full JSON in the GOOGLE_CREDENTIALS_JSON environment variable (plain JSON,
    or the same JSON encoded as base64). Locally, credentials.json is used.
    """

    raw = _read_env("GOOGLE_CREDENTIALS_JSON").strip().strip('"').strip("'").strip()

    if raw:
        if not raw.startswith("{"):
            raw = base64.b64decode(raw).decode("utf-8")

        # strict=False tolerates real line breaks inside the private key.
        return service_account.Credentials.from_service_account_info(
            json.loads(raw, strict=False),
            scopes=SCOPES
        )

    if not os.path.exists(SERVICE_ACCOUNT_FILE):
        # Names only, never values: helps spot a mistyped variable name.
        similar = sorted(
            key for key in os.environ
            if "GOOGLE" in key.upper() or "CRED" in key.upper()
        )
        raise RuntimeError(
            "Google Calendar is not configured on this server: the "
            "GOOGLE_CREDENTIALS_JSON environment variable is empty or missing "
            f"(similar variable names seen: {similar or 'none'}). Set it to the "
            "full contents of credentials.json and redeploy."
        )

    return service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        scopes=SCOPES
    )


def get_calendar_service():

    credentials = load_credentials()

    return build(
        "calendar",
        "v3",
        credentials=credentials
    )


def create_calendar_event(
    trainer_name,
    client_name,
    client_email,
    session_date,
    session_time,
    session_number=None
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    TRAINER_COLORS = {

        "Carles": "1",
        "David": "2",
        "Guille": "3",
        "Matilda": "4"

    }

    title = f"🏋️ ThundBalance • {client_name}"

    if session_number:

        title += f" ({session_number})"

    event = {

        "summary": title,

        "location": "ThundBalance Personal Training Studio",

        "description": f"""
🏋️ THUNDBALANCE

Client
{client_name}

Trainer
{trainer_name}

Session
{session_number if session_number else "-"}

Email
{client_email}

Duration
60 minutes

Automatically generated by ThundBalance.
""",

        "colorId": TRAINER_COLORS.get(
            trainer_name,
            "1"
        ),

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },
        # "attendees": [
        #
        #     {
        #         "email": client_email
        #     }
        #
        # ],

    }

    print("BEFORE GOOGLE")

    created_event = service.events().insert(
        calendarId=CALENDAR_ID,
        body=event
    ).execute()

    print("AFTER GOOGLE")
    print(created_event)

    print(
        "EVENT CREATED:",
        created_event["id"]
    )

    return created_event["id"]

def delete_calendar_event(
    event_id
):

    service = get_calendar_service()

    service.events().delete(
        calendarId=CALENDAR_ID,
        eventId=event_id
    ).execute()

    print("EVENT DELETED:", event_id)


def update_calendar_event(
    event_id,
    session_date,
    session_time
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    print("EVENT ID:", event_id)

    updated_event = {

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        }

    }

    print("UPDATING EVENT...")

    service.events().patch(
        calendarId=CALENDAR_ID,
        eventId=event_id,
        body=updated_event
    ).execute()

    print("EVENT UPDATED:", event_id)



def create_trial_session_event(
    full_name,
    email,
    phone,
    goal,
    experience,
    session_date,
    session_time,
    trainer_name=None
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    event = {

        "summary": f"🟨 TRIAL • {full_name}",

        "description": f"""
Trial Session Request

Name: {full_name}

Email: {email}

Phone: {phone}

Goal: {goal}

Experience: {experience}
{f"{chr(10)}Trainer: {trainer_name}{chr(10)}" if trainer_name else ""}""",

        "colorId": "5",

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        }

    }

    created_event = service.events().insert(
        calendarId=CALENDAR_ID,
        body=event
    ).execute()

    print("TRIAL EVENT CREATED:", created_event["id"])

    return created_event["id"]


def clear_calendar():

    service = get_calendar_service()

    events = service.events().list(
        calendarId=CALENDAR_ID
    ).execute()

    items = events.get("items", [])

    for event in items:

        try:

            service.events().delete(
                calendarId=CALENDAR_ID,
                eventId=event["id"]
            ).execute()

            print("Deleted:", event["id"])

        except Exception:

            pass

    print("GOOGLE CALENDAR CLEARED")


def list_calendar_events(time_min, time_max):
    """Events between two RFC3339 instants, in Europe/Madrid time.

    Recurring events are expanded and results are paginated until Google has
    no more pages, so a busy month is returned completely.
    """

    service = get_calendar_service()
    events = []
    page_token = None

    while True:
        response = service.events().list(
            calendarId=CALENDAR_ID,
            timeMin=time_min,
            timeMax=time_max,
            singleEvents=True,
            orderBy="startTime",
            timeZone="Europe/Madrid",
            maxResults=250,
            pageToken=page_token
        ).execute()

        events.extend(response.get("items", []))
        page_token = response.get("nextPageToken")

        if not page_token:
            return events
