from google.oauth2 import service_account
from googleapiclient.discovery import build
from datetime import datetime, timedelta

SCOPES = [
    "https://www.googleapis.com/auth/calendar"
]

SERVICE_ACCOUNT_FILE = "credentials.json"

CALENDAR_ID = "5b958f681e0f3a7ab9316d1955367098481d33c5682578df1fca743a260d0490@group.calendar.google.com"


def get_calendar_service():

    credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        scopes=SCOPES
    )

    return build(
        "calendar",
        "v3",
        credentials=credentials
    )


def create_calendar_event(
    trainer_name,
    client_name,
    client_email,
    session_date,
    session_time,
    session_number=None
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    TRAINER_COLORS = {

        "Carles": "1",
        "David": "2",
        "Guille": "3",
        "Matilda": "4"

    }

    title = f"🏋️ ThundBalance • {client_name}"

    if session_number:

        title += f" ({session_number})"

    event = {

        "summary": title,

        "location": "ThundBalance Personal Training Studio",

        "description": f"""
🏋️ THUNDBALANCE

Client
{client_name}

Trainer
{trainer_name}

Session
{session_number if session_number else "-"}

Email
{client_email}

Duration
60 minutes

Automatically generated by ThundBalance.
""",

        "colorId": TRAINER_COLORS.get(
            trainer_name,
            "1"
        ),

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },
        # "attendees": [
        #
        #     {
        #         "email": client_email
        #     }
        #
        # ],

    }

    print("BEFORE GOOGLE")

    created_event = service.events().insert(
        calendarId=CALENDAR_ID,
        body=event
    ).execute()

    print("AFTER GOOGLE")
    print(created_event)

    print(
        "EVENT CREATED:",
        created_event["id"]
    )

    return created_event["id"]

def delete_calendar_event(
    event_id
):

    service = get_calendar_service()

    service.events().delete(
        calendarId=CALENDAR_ID,
        eventId=event_id
    ).execute()

    print("EVENT DELETED:", event_id)


def update_calendar_event(
    event_id,
    session_date,
    session_time
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    print("EVENT ID:", event_id)

    updated_event = {

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        }

    }

    print("UPDATING EVENT...")

    service.events().patch(
        calendarId=CALENDAR_ID,
        eventId=event_id,
        body=updated_event
    ).execute()

    print("EVENT UPDATED:", event_id)



def create_trial_session_event(
    full_name,
    email,
    phone,
    goal,
    experience,
    session_date,
    session_time
):

    service = get_calendar_service()

    start_datetime = datetime.fromisoformat(
        f"{session_date} {session_time}"
    )

    end_datetime = start_datetime + timedelta(hours=1)

    event = {

        "summary": f"🟨 TRIAL • {full_name}",

        "description": f"""
Trial Session Request

Name: {full_name}

Email: {email}

Phone: {phone}

Goal: {goal}

Experience: {experience}
""",

        "colorId": "5",

        "start": {
            "dateTime": start_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        },

        "end": {
            "dateTime": end_datetime.isoformat(),
            "timeZone": "Europe/Madrid"
        }

    }

    created_event = service.events().insert(
        calendarId=CALENDAR_ID,
        body=event
    ).execute()

    print("TRIAL EVENT CREATED:", created_event["id"])

    return created_event["id"]


def clear_calendar():

    service = get_calendar_service()

    events = service.events().list(
        calendarId=CALENDAR_ID
    ).execute()

    items = events.get("items", [])

    for event in items:

        try:

            service.events().delete(
                calendarId=CALENDAR_ID,
                eventId=event["id"]
            ).execute()

            print("Deleted:", event["id"])

        except Exception:

            pass

    print("GOOGLE CALENDAR CLEARED")