// Interface strings for the admin panel (English + Spanish). Kept apart from
// the public site's translations so the admin language can be chosen
// independently of the language visitors see.
export const adminText = {
  en: {
    brand_sub: 'Admin panel',
    nav_overview: 'Overview',
    nav_requests: 'Requests',
    nav_clients: 'Clients',
    nav_trials: 'Trial sessions',
    nav_trainers: 'Trainers',
    nav_videos: 'Training videos',
    nav_landing: 'Landing page',
    nav_site: 'View website',
    nav_logout: 'Log out',
    nav_menu: 'Menu',
    nav_close: 'Close menu',
    language: 'Language',

    overview_sub: "Here's what's happening at ThundBalance.",
    stat_clients: 'Clients',
    stat_trainers: 'Trainers',
    stat_sessions: 'Sessions booked',
    stat_trials: 'Trial requests',
    stat_pending: 'Pending requests',
    pending_hint_some: 'Waiting for your approval',
    pending_hint_none: 'All caught up',
    week_title: 'Sessions this week',
    week_sub: 'Booked sessions for the next 7 days',
    today: 'Today',
    upcoming_title: 'Upcoming sessions',
    upcoming_empty: 'No upcoming sessions.',
    pending_title: 'Pending requests',
    pending_empty: 'No requests are waiting for you.',
    view_all: 'View all',
    quick_title: 'Quick actions',
    qa_landing: 'Edit landing page',
    qa_landing_desc: 'Change texts, images, colors and sections',
    qa_videos: 'Training videos',
    qa_videos_desc: 'Manage the Training Tips library',
    qa_clients: 'Clients',
    qa_clients_desc: 'Plans, progress and sessions',
    load_error: 'We could not load this data.',
    retry: 'Try again',
    refresh: 'Refresh',

    req_title: 'Training requests',
    req_sub: 'Review, approve or decline what clients ask for.',
    req_all: 'All',
    req_pending: 'Pending',
    req_approved: 'Approved',
    req_rejected: 'Declined',
    req_search: 'Search by client or package…',
    req_empty: 'No requests match this filter.',
    req_per_week: 'per week',
    req_days: 'Days',
    req_time: 'Time',
    req_reason: 'Reason',
    req_approve: 'Approve',
    req_reject: 'Decline',
    approve_title: 'Approve request',
    approve_sub: 'Assign a trainer and a start date. The sessions are created and added to the calendar.',
    trainer: 'Trainer',
    select_trainer: 'Select a trainer',
    start_date: 'Start date',
    package: 'Package',
    package_keep: 'Requested package',
    frequency: 'Sessions per week',
    sessions_label: 'sessions',
    will_create: 'This will create',
    approve_confirm: 'Approve and create sessions',
    approving: 'Creating sessions…',
    approving_hint: 'This can take up to a minute.',
    need_trainer_date: 'Choose a trainer and a start date.',
    reject_title: 'Decline request',
    reject_sub: 'The client will see this request as declined.',
    reject_reason: 'Reason (optional)',
    reject_reason_ph: 'Tell the client why, e.g. no availability at that time.',
    reject_confirm: 'Decline request',
    rejecting: 'Declining…',
    cancel: 'Cancel',
    approved_ok: 'Request approved. Sessions created.',
    rejected_ok: 'Request declined.',
    action_error: 'Could not complete the action.',

    nav_sessions: 'Calendar',
    nav_plans: 'Plans',
    clients_title: 'Clients',
    clients_sub: 'Everyone who trains with ThundBalance, their plan and progress.',
    cl_search: 'Search by name or email…',
    cl_all: 'All',
    cl_with_plan: 'With plan',
    cl_no_plan_filter: 'No plan',
    cl_pending: 'Pending request',
    cl_empty: 'No clients match this search.',
    cl_none: 'There are no clients yet.',
    cl_no_plan: 'No plan',
    cl_sessions: 'sessions',
    cl_next: 'Next session',
    cl_no_next: 'None scheduled',
    cl_progress: 'Progress',
    cl_completed: 'completed',
    cl_upcoming: 'upcoming',
    cl_contact: 'Contact',
    cl_phone: 'Phone',
    cl_city: 'City',
    cl_address: 'Address',
    cl_plan_section: 'Plan',
    cl_assign: 'Change plan',
    cl_assign_ph: 'Select a plan',
    cl_assign_save: 'Assign plan',
    cl_plan_saved: 'Plan updated.',
    cl_sessions_title: 'Sessions',
    cl_no_sessions: 'This client has no sessions yet.',
    cl_cancel_session: 'Cancel',
    cl_cancel_title: 'Cancel this session?',
    cl_cancel_text: 'It is removed from the calendar and the client will see it as cancelled.',
    cl_cancel_keep: 'Keep session',
    cl_cancel_do: 'Cancel session',
    cl_cancelled_ok: 'Session cancelled.',
    cl_detail_error: 'We could not load this client.',
    st_booked: 'Booked',
    st_cancelled: 'Cancelled',

    ss_title: 'Sessions',
    ss_sub: 'The whole calendar: who trains, with whom and when.',
    ss_all_trainers: 'All trainers',
    ss_show_cancelled: 'Show cancelled',
    ss_today: 'Today',
    ss_day_empty: 'No sessions on this day.',
    ss_month_sessions: 'sessions this month',

    pl_title: 'Plans',
    pl_sub: 'The packages clients can choose from.',
    pl_new: 'New plan',
    pl_edit_title: 'Edit plan',
    pl_new_title: 'New plan',
    pl_name: 'Name',
    pl_months: 'Duration (months)',
    pl_weeks: 'Duration (weeks)',
    pl_weeks_hint: 'Used to calculate how many sessions are created (weeks × sessions per week).',
    pl_price: 'Price (€)',
    pl_save: 'Save plan',
    pl_saving: 'Saving…',
    pl_delete: 'Delete',
    pl_delete_title: 'Delete this plan?',
    pl_delete_text: 'This cannot be undone. Plans that clients already use cannot be deleted.',
    pl_created: 'Plan created.',
    pl_updated: 'Plan updated.',
    pl_deleted: 'Plan deleted.',
    pl_empty: 'There are no plans yet.',
    pl_invalid: 'Fill in every field with valid values.',
    pl_months_short: 'months',
    pl_weeks_short: 'weeks',

    videos_title: 'Training videos',
    ed_back: 'Admin',
    ed_title: 'Page editor',
    ed_desktop: 'Desktop',
    ed_tablet: 'Tablet',
    ed_mobile: 'Mobile',
    ed_undo: 'Undo',
    ed_redo: 'Redo',
    ed_saved: 'Saved',
    ed_unsaved: 'Unsaved changes',
    ed_saving: 'Saving…',
    ed_preview: 'Preview',
    ed_save: 'Save',
    ed_publish: 'Publish',
    ed_publishing: 'Publishing…',
    ed_more: 'More',
    ed_hide_sidebar: 'Hide sections menu',
    ed_show_sidebar: 'Show sections menu',
    ed_restore: 'Restore default page',
    ed_restore_title: 'Restore the default page?',
    ed_restore_text: 'Your current draft is replaced by the original page. The published site does not change until you publish again.',
    ed_restore_do: 'Restore',
    ed_cancel: 'Cancel',
    ed_sections: 'Sections',
    ed_site_style: 'Site style',
    ed_add_section: 'Add section',
    ed_add_section_sub: 'Choose what to add at the end of the page.',
    ed_hide: 'Hide section',
    ed_show: 'Show section',
    ed_duplicate: 'Duplicate',
    ed_delete: 'Delete',
    ed_delete_title: 'Delete this section?',
    ed_delete_text: 'The section and everything in it will be removed.',
    ed_fixed: 'Fixed',
    ed_drag_hint: 'Drag to reorder',
    ed_tip: 'Click any element to edit it. Drag it to move it. Double-click a text to type.',
    ed_tab_content: 'Content',
    ed_tab_style: 'Style',
    ed_tab_position: 'Position',
    av_hint: 'Only trainers who work then can be chosen:',
    av_unavailable: 'not available',
    av_works: 'works',
    av_none: 'No trainer works at that time, so this request cannot be approved as asked.',
    tn_title: 'Trainers',
    tn_sub: 'Working hours of each trainer. Sessions can only be booked inside these hours.',
    tn_note: 'Every session lasts 1 hour. A trainer who works until 14:00 can start a session at 13:00 at the latest.',
    tn_works: 'Works',
    tn_off: 'Day off',
    tn_from: 'From',
    tn_to: 'Until',
    tn_save: 'Save hours',
    tn_saving: 'Saving…',
    tn_saved: 'Hours saved.',
    tn_apply_week: 'Copy Monday to Mon–Fri',
    tn_unsaved: 'Unsaved changes',
    tn_invalid: 'The end time must be after the start time.',
    tn_empty: 'There are no active trainers.',
    tn_add: 'Add trainer',
    tn_new_title: 'New trainer',
    tn_new_sub: 'Add the trainer and the hours they work. Clients can book them only inside these hours.',
    tn_name: 'Name',
    tn_specialty: 'Specialty (optional)',
    tn_specialty_ph: 'e.g. Strength, Mobility…',
    tn_create: 'Add trainer',
    tn_creating: 'Adding…',
    tn_created: 'Trainer added.',
    tn_remove: 'Remove',
    tn_remove_title: 'Remove this trainer?',
    tn_remove_text: 'They will no longer be offered anywhere on the site. Trainers with upcoming sessions cannot be removed.',
    tn_removed: 'Trainer deleted.',
    tn_archived: 'Trainer removed. Their past sessions are kept, so they are hidden instead of deleted.',
    tn_days_word: 'days',
    cal_title: 'Calendar',
    cal_sub: 'Live from Google Calendar: every session and trial in one place.',
    cal_week: 'Week',
    cal_month: 'Month',
    cal_today: 'Today',
    cal_prev: 'Previous',
    cal_next: 'Next',
    cal_synced: 'Synced with Google Calendar',
    cal_legend_trial: 'Trial session',
    cal_legend_other: 'Other event',
    cal_no_events: 'Nothing scheduled this day.',
    cal_events_count: 'events',
    cal_type_session: 'Training session',
    cal_type_trial: 'Trial session',
    cal_type_other: 'Calendar event',
    cal_client: 'Client',
    cal_when: 'When',
    cal_all_day: 'All day',
    cal_open_google: 'Open in Google Calendar',
    cal_view_client: 'View clients',
    cal_other_hint: 'This event was added directly in Google Calendar, so it is not linked to a client.',
    cal_more: 'more',
    tr_title: 'Trial sessions',
    tr_sub: 'People who asked to try a free session. Approve with a trainer to add it to the calendar.',
    tr_all: 'All',
    tr_pending: 'Pending',
    tr_approved: 'Approved',
    tr_rejected: 'Declined',
    tr_cancelled: 'Cancelled',
    tr_search: 'Search by name, email or phone…',
    tr_empty: 'No trial requests match this filter.',
    tr_requested_for: 'Requested for',
    tr_goal: 'Goal',
    tr_experience: 'Experience',
    tr_age: 'Age',
    tr_trainer: 'Trainer',
    tr_approve_title: 'Approve trial session',
    tr_approve_sub: 'Choose the trainer. The session is added to the Google Calendar.',
    tr_approve_confirm: 'Approve and add to calendar',
    tr_approving: 'Adding to calendar…',
    tr_approved_ok: 'Trial session approved and added to the calendar.',
    tr_reject_title: 'Decline trial session',
    tr_reject_sub: 'The request is marked as declined.',
    tr_rejected_ok: 'Trial request declined.',
    tr_cancel_title: 'Cancel this trial session?',
    tr_cancel_text: 'It is removed from the Google Calendar.',
    tr_cancel_do: 'Cancel session',
    tr_cancel_keep: 'Keep it',
    tr_cancelled_ok: 'Trial session cancelled.',
    tr_call: 'Call',
    tr_email: 'Email',
    vd_sub: 'The library shown on the Training Tips page.',
    vd_add: 'Add video',
    vd_new_title: 'Add video',
    vd_edit_title: 'Edit video',
    vd_title: 'Title',
    vd_desc: 'Description',
    vd_upload: 'Upload video',
    vd_replace: 'Replace video',
    vd_uploading: 'Uploading…',
    vd_uploaded: 'Video uploaded.',
    vd_save: 'Save video',
    vd_saving: 'Saving…',
    vd_empty: 'No videos yet.',
    vd_delete_title: 'Delete this video?',
    vd_delete_text: 'This cannot be undone.',
    vd_saved: 'Video saved.',
    vd_deleted: 'Video deleted.',
    vd_required: 'A title and a video are required.',
    vd_upload_error: 'Could not upload the video. Try a smaller file.',
    vd_up: 'Move up',
    vd_down: 'Move down',
    vd_edit: 'Edit',
    vd_remove: 'Delete',

    lg_title: 'Admin access',
    lg_sub: 'Sign in with the administrator account.',
    lg_email: 'Email',
    lg_password: 'Password',
    lg_submit: 'Sign in',
    lg_signing: 'Signing in…',
    lg_denied: 'This account does not have administrator access.',
    lg_invalid: 'Incorrect email or password.',
    lg_checking: 'Checking access…',
    lg_back: '← Back to the website',

    st_pending: 'Pending',
    st_approved: 'Approved',
    st_rejected: 'Declined',
    days: {
      Monday: 'Mon', Tuesday: 'Tue', Wednesday: 'Wed', Thursday: 'Thu',
      Friday: 'Fri', Saturday: 'Sat', Sunday: 'Sun'
    },
    days_full: {
      Monday: 'Monday', Tuesday: 'Tuesday', Wednesday: 'Wednesday', Thursday: 'Thursday',
      Friday: 'Friday', Saturday: 'Saturday', Sunday: 'Sunday'
    }
  },
  es: {
    brand_sub: 'Panel de administración',
    nav_overview: 'Resumen',
    nav_requests: 'Solicitudes',
    nav_clients: 'Clientes',
    nav_trials: 'Sesiones de prueba',
    nav_trainers: 'Entrenadores',
    nav_videos: 'Vídeos de entrenamiento',
    nav_landing: 'Página web',
    nav_site: 'Ver la web',
    nav_logout: 'Cerrar sesión',
    nav_menu: 'Menú',
    nav_close: 'Cerrar menú',
    language: 'Idioma',

    overview_sub: 'Esto es lo que está pasando en ThundBalance.',
    stat_clients: 'Clientes',
    stat_trainers: 'Entrenadores',
    stat_sessions: 'Sesiones reservadas',
    stat_trials: 'Pruebas pendientes',
    stat_pending: 'Solicitudes pendientes',
    pending_hint_some: 'Esperan tu aprobación',
    pending_hint_none: 'Todo al día',
    week_title: 'Sesiones de esta semana',
    week_sub: 'Sesiones reservadas en los próximos 7 días',
    today: 'Hoy',
    upcoming_title: 'Próximas sesiones',
    upcoming_empty: 'No hay sesiones próximas.',
    pending_title: 'Solicitudes pendientes',
    pending_empty: 'No hay solicitudes esperando.',
    view_all: 'Ver todas',
    quick_title: 'Accesos rápidos',
    qa_landing: 'Editar la página web',
    qa_landing_desc: 'Cambia textos, imágenes, colores y secciones',
    qa_videos: 'Vídeos de entrenamiento',
    qa_videos_desc: 'Gestiona la biblioteca de Training Tips',
    qa_clients: 'Clientes',
    qa_clients_desc: 'Planes, progreso y sesiones',
    load_error: 'No pudimos cargar estos datos.',
    retry: 'Reintentar',
    refresh: 'Actualizar',

    req_title: 'Solicitudes de entrenamiento',
    req_sub: 'Revisa, aprueba o rechaza lo que piden los clientes.',
    req_all: 'Todas',
    req_pending: 'Pendientes',
    req_approved: 'Aprobadas',
    req_rejected: 'Rechazadas',
    req_search: 'Buscar por cliente o paquete…',
    req_empty: 'No hay solicitudes con este filtro.',
    req_per_week: 'por semana',
    req_days: 'Días',
    req_time: 'Hora',
    req_reason: 'Motivo',
    req_approve: 'Aprobar',
    req_reject: 'Rechazar',
    approve_title: 'Aprobar solicitud',
    approve_sub: 'Asigna un entrenador y una fecha de inicio. Se crean las sesiones y se añaden al calendario.',
    trainer: 'Entrenador',
    select_trainer: 'Selecciona un entrenador',
    start_date: 'Fecha de inicio',
    package: 'Paquete',
    package_keep: 'Paquete solicitado',
    frequency: 'Sesiones por semana',
    sessions_label: 'sesiones',
    will_create: 'Se crearán',
    approve_confirm: 'Aprobar y crear sesiones',
    approving: 'Creando sesiones…',
    approving_hint: 'Puede tardar hasta un minuto.',
    need_trainer_date: 'Elige un entrenador y una fecha de inicio.',
    reject_title: 'Rechazar solicitud',
    reject_sub: 'El cliente verá esta solicitud como rechazada.',
    reject_reason: 'Motivo (opcional)',
    reject_reason_ph: 'Cuéntale al cliente por qué, p. ej. no hay disponibilidad a esa hora.',
    reject_confirm: 'Rechazar solicitud',
    rejecting: 'Rechazando…',
    cancel: 'Cancelar',
    approved_ok: 'Solicitud aprobada. Sesiones creadas.',
    rejected_ok: 'Solicitud rechazada.',
    action_error: 'No se pudo completar la acción.',

    nav_sessions: 'Calendario',
    nav_plans: 'Planes',
    clients_title: 'Clientes',
    clients_sub: 'Todos los que entrenan en ThundBalance, con su plan y progreso.',
    cl_search: 'Buscar por nombre o email…',
    cl_all: 'Todos',
    cl_with_plan: 'Con plan',
    cl_no_plan_filter: 'Sin plan',
    cl_pending: 'Solicitud pendiente',
    cl_empty: 'Ningún cliente coincide con la búsqueda.',
    cl_none: 'Todavía no hay clientes.',
    cl_no_plan: 'Sin plan',
    cl_sessions: 'sesiones',
    cl_next: 'Próxima sesión',
    cl_no_next: 'Ninguna programada',
    cl_progress: 'Progreso',
    cl_completed: 'completadas',
    cl_upcoming: 'próximas',
    cl_contact: 'Contacto',
    cl_phone: 'Teléfono',
    cl_city: 'Ciudad',
    cl_address: 'Dirección',
    cl_plan_section: 'Plan',
    cl_assign: 'Cambiar plan',
    cl_assign_ph: 'Selecciona un plan',
    cl_assign_save: 'Asignar plan',
    cl_plan_saved: 'Plan actualizado.',
    cl_sessions_title: 'Sesiones',
    cl_no_sessions: 'Este cliente aún no tiene sesiones.',
    cl_cancel_session: 'Cancelar',
    cl_cancel_title: '¿Cancelar esta sesión?',
    cl_cancel_text: 'Se elimina del calendario y el cliente la verá como cancelada.',
    cl_cancel_keep: 'Mantener sesión',
    cl_cancel_do: 'Cancelar sesión',
    cl_cancelled_ok: 'Sesión cancelada.',
    cl_detail_error: 'No pudimos cargar este cliente.',
    st_booked: 'Reservada',
    st_cancelled: 'Cancelada',

    ss_title: 'Sesiones',
    ss_sub: 'Todo el calendario: quién entrena, con quién y cuándo.',
    ss_all_trainers: 'Todos los entrenadores',
    ss_show_cancelled: 'Mostrar canceladas',
    ss_today: 'Hoy',
    ss_day_empty: 'No hay sesiones este día.',
    ss_month_sessions: 'sesiones este mes',

    pl_title: 'Planes',
    pl_sub: 'Los paquetes que pueden elegir los clientes.',
    pl_new: 'Nuevo plan',
    pl_edit_title: 'Editar plan',
    pl_new_title: 'Nuevo plan',
    pl_name: 'Nombre',
    pl_months: 'Duración (meses)',
    pl_weeks: 'Duración (semanas)',
    pl_weeks_hint: 'Sirve para calcular cuántas sesiones se crean (semanas × sesiones por semana).',
    pl_price: 'Precio (€)',
    pl_save: 'Guardar plan',
    pl_saving: 'Guardando…',
    pl_delete: 'Eliminar',
    pl_delete_title: '¿Eliminar este plan?',
    pl_delete_text: 'No se puede deshacer. Los planes que ya usan clientes no se pueden eliminar.',
    pl_created: 'Plan creado.',
    pl_updated: 'Plan actualizado.',
    pl_deleted: 'Plan eliminado.',
    pl_empty: 'Todavía no hay planes.',
    pl_invalid: 'Rellena todos los campos con valores válidos.',
    pl_months_short: 'meses',
    pl_weeks_short: 'semanas',

    videos_title: 'Vídeos de entrenamiento',
    ed_back: 'Admin',
    ed_title: 'Editor de la página',
    ed_desktop: 'Escritorio',
    ed_tablet: 'Tablet',
    ed_mobile: 'Móvil',
    ed_undo: 'Deshacer',
    ed_redo: 'Rehacer',
    ed_saved: 'Guardado',
    ed_unsaved: 'Cambios sin guardar',
    ed_saving: 'Guardando…',
    ed_preview: 'Vista previa',
    ed_save: 'Guardar',
    ed_publish: 'Publicar',
    ed_publishing: 'Publicando…',
    ed_more: 'Más',
    ed_hide_sidebar: 'Ocultar menú de secciones',
    ed_show_sidebar: 'Mostrar menú de secciones',
    ed_restore: 'Restaurar la página original',
    ed_restore_title: '¿Restaurar la página original?',
    ed_restore_text: 'Tu borrador actual se sustituye por la página original. La web publicada no cambia hasta que vuelvas a publicar.',
    ed_restore_do: 'Restaurar',
    ed_cancel: 'Cancelar',
    ed_sections: 'Secciones',
    ed_site_style: 'Estilo del sitio',
    ed_add_section: 'Añadir sección',
    ed_add_section_sub: 'Elige qué añadir al final de la página.',
    ed_hide: 'Ocultar sección',
    ed_show: 'Mostrar sección',
    ed_duplicate: 'Duplicar',
    ed_delete: 'Eliminar',
    ed_delete_title: '¿Eliminar esta sección?',
    ed_delete_text: 'Se eliminará la sección y todo su contenido.',
    ed_fixed: 'Fija',
    ed_drag_hint: 'Arrastra para reordenar',
    ed_tip: 'Haz clic en cualquier elemento para editarlo. Arrástralo para moverlo. Doble clic en un texto para escribir.',
    ed_tab_content: 'Contenido',
    ed_tab_style: 'Estilo',
    ed_tab_position: 'Posición',
    av_hint: 'Solo se pueden elegir entrenadores que trabajan entonces:',
    av_unavailable: 'no disponible',
    av_works: 'trabaja',
    av_none: 'Ningún entrenador trabaja a esa hora, así que esta solicitud no se puede aprobar tal como se pidió.',
    tn_title: 'Entrenadores',
    tn_sub: 'Horario de trabajo de cada entrenador. Las sesiones solo se pueden reservar dentro de estos horarios.',
    tn_note: 'Cada sesión dura 1 hora. Un entrenador que trabaja hasta las 14:00 puede empezar una sesión a las 13:00 como máximo.',
    tn_works: 'Trabaja',
    tn_off: 'Día libre',
    tn_from: 'Desde',
    tn_to: 'Hasta',
    tn_save: 'Guardar horario',
    tn_saving: 'Guardando…',
    tn_saved: 'Horario guardado.',
    tn_apply_week: 'Copiar el lunes a lun–vie',
    tn_unsaved: 'Cambios sin guardar',
    tn_invalid: 'La hora de fin debe ser posterior a la de inicio.',
    tn_empty: 'No hay entrenadores activos.',
    tn_add: 'Añadir entrenador',
    tn_new_title: 'Nuevo entrenador',
    tn_new_sub: 'Añade al entrenador y las horas que trabaja. Los clientes solo podrán reservarlo dentro de ese horario.',
    tn_name: 'Nombre',
    tn_specialty: 'Especialidad (opcional)',
    tn_specialty_ph: 'p. ej. Fuerza, Movilidad…',
    tn_create: 'Añadir entrenador',
    tn_creating: 'Añadiendo…',
    tn_created: 'Entrenador añadido.',
    tn_remove: 'Quitar',
    tn_remove_title: '¿Quitar a este entrenador?',
    tn_remove_text: 'Dejará de ofrecerse en toda la web. No se puede quitar a entrenadores con sesiones próximas.',
    tn_removed: 'Entrenador eliminado.',
    tn_archived: 'Entrenador quitado. Sus sesiones pasadas se conservan, así que queda oculto en lugar de eliminado.',
    tn_days_word: 'días',
    cal_title: 'Calendario',
    cal_sub: 'En directo desde Google Calendar: todas las sesiones y pruebas en un solo lugar.',
    cal_week: 'Semana',
    cal_month: 'Mes',
    cal_today: 'Hoy',
    cal_prev: 'Anterior',
    cal_next: 'Siguiente',
    cal_synced: 'Sincronizado con Google Calendar',
    cal_legend_trial: 'Sesión de prueba',
    cal_legend_other: 'Otro evento',
    cal_no_events: 'No hay nada programado este día.',
    cal_events_count: 'eventos',
    cal_type_session: 'Sesión de entrenamiento',
    cal_type_trial: 'Sesión de prueba',
    cal_type_other: 'Evento del calendario',
    cal_client: 'Cliente',
    cal_when: 'Cuándo',
    cal_all_day: 'Todo el día',
    cal_open_google: 'Abrir en Google Calendar',
    cal_view_client: 'Ver clientes',
    cal_other_hint: 'Este evento se añadió directamente en Google Calendar, así que no está vinculado a ningún cliente.',
    cal_more: 'más',
    tr_title: 'Sesiones de prueba',
    tr_sub: 'Personas que pidieron probar una sesión gratuita. Aprueba con un entrenador para añadirla al calendario.',
    tr_all: 'Todas',
    tr_pending: 'Pendientes',
    tr_approved: 'Aprobadas',
    tr_rejected: 'Rechazadas',
    tr_cancelled: 'Canceladas',
    tr_search: 'Buscar por nombre, email o teléfono…',
    tr_empty: 'No hay solicitudes de prueba con este filtro.',
    tr_requested_for: 'Solicitada para',
    tr_goal: 'Objetivo',
    tr_experience: 'Experiencia',
    tr_age: 'Edad',
    tr_trainer: 'Entrenador',
    tr_approve_title: 'Aprobar sesión de prueba',
    tr_approve_sub: 'Elige el entrenador. La sesión se añade al Google Calendar.',
    tr_approve_confirm: 'Aprobar y añadir al calendario',
    tr_approving: 'Añadiendo al calendario…',
    tr_approved_ok: 'Sesión de prueba aprobada y añadida al calendario.',
    tr_reject_title: 'Rechazar sesión de prueba',
    tr_reject_sub: 'La solicitud se marca como rechazada.',
    tr_rejected_ok: 'Solicitud de prueba rechazada.',
    tr_cancel_title: '¿Cancelar esta sesión de prueba?',
    tr_cancel_text: 'Se elimina del Google Calendar.',
    tr_cancel_do: 'Cancelar sesión',
    tr_cancel_keep: 'Mantenerla',
    tr_cancelled_ok: 'Sesión de prueba cancelada.',
    tr_call: 'Llamar',
    tr_email: 'Email',
    vd_sub: 'La biblioteca que se muestra en la página de Training Tips.',
    vd_add: 'Añadir vídeo',
    vd_new_title: 'Añadir vídeo',
    vd_edit_title: 'Editar vídeo',
    vd_title: 'Título',
    vd_desc: 'Descripción',
    vd_upload: 'Subir vídeo',
    vd_replace: 'Reemplazar vídeo',
    vd_uploading: 'Subiendo…',
    vd_uploaded: 'Vídeo subido.',
    vd_save: 'Guardar vídeo',
    vd_saving: 'Guardando…',
    vd_empty: 'Todavía no hay vídeos.',
    vd_delete_title: '¿Eliminar este vídeo?',
    vd_delete_text: 'No se puede deshacer.',
    vd_saved: 'Vídeo guardado.',
    vd_deleted: 'Vídeo eliminado.',
    vd_required: 'Se necesitan un título y un vídeo.',
    vd_upload_error: 'No se pudo subir el vídeo. Prueba con un archivo más pequeño.',
    vd_up: 'Subir',
    vd_down: 'Bajar',
    vd_edit: 'Editar',
    vd_remove: 'Eliminar',

    lg_title: 'Acceso de administrador',
    lg_sub: 'Inicia sesión con la cuenta de administrador.',
    lg_email: 'Email',
    lg_password: 'Contraseña',
    lg_submit: 'Entrar',
    lg_signing: 'Entrando…',
    lg_denied: 'Esta cuenta no tiene acceso de administrador.',
    lg_invalid: 'Email o contraseña incorrectos.',
    lg_checking: 'Comprobando acceso…',
    lg_back: '← Volver a la web',

    st_pending: 'Pendiente',
    st_approved: 'Aprobada',
    st_rejected: 'Rechazada',
    days: {
      Monday: 'Lun', Tuesday: 'Mar', Wednesday: 'Mié', Thursday: 'Jue',
      Friday: 'Vie', Saturday: 'Sáb', Sunday: 'Dom'
    },
    days_full: {
      Monday: 'Lunes', Tuesday: 'Martes', Wednesday: 'Miércoles', Thursday: 'Jueves',
      Friday: 'Viernes', Saturday: 'Sábado', Sunday: 'Domingo'
    }
  }
}
